# Generated by Django 5.0 on 2024-02-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
